// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUuXyyR1Y-ss8QHAMHQdNQuM923zP9n1g',
    appId: '1:532692727175:web:f97a9c8eaac85f1ac34f22',
    messagingSenderId: '532692727175',
    projectId: 'lab10-firebase-auth',
    authDomain: 'lab10-firebase-auth.firebaseapp.com',
    storageBucket: 'lab10-firebase-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU24BoLadMugl6Vj5Db_cVPfBpSHiK7ik',
    appId: '1:532692727175:android:4fbc0c1e173211b9c34f22',
    messagingSenderId: '532692727175',
    projectId: 'lab10-firebase-auth',
    storageBucket: 'lab10-firebase-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8CaBIAQAUgOlHc3NgqxABJ9m1k9o4xEA',
    appId: '1:532692727175:ios:b1daf67fb5358fd2c34f22',
    messagingSenderId: '532692727175',
    projectId: 'lab10-firebase-auth',
    storageBucket: 'lab10-firebase-auth.firebasestorage.app',
    androidClientId: '532692727175-bi2dcjt0i42f9ke7v0mau9rpka9utn4o.apps.googleusercontent.com',
    iosClientId: '532692727175-cbkvb54coaaruc2iv14jrm6oavedibm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab104Firebasegooglesignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8CaBIAQAUgOlHc3NgqxABJ9m1k9o4xEA',
    appId: '1:532692727175:ios:b1daf67fb5358fd2c34f22',
    messagingSenderId: '532692727175',
    projectId: 'lab10-firebase-auth',
    storageBucket: 'lab10-firebase-auth.firebasestorage.app',
    androidClientId: '532692727175-bi2dcjt0i42f9ke7v0mau9rpka9utn4o.apps.googleusercontent.com',
    iosClientId: '532692727175-cbkvb54coaaruc2iv14jrm6oavedibm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab104Firebasegooglesignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUuXyyR1Y-ss8QHAMHQdNQuM923zP9n1g',
    appId: '1:532692727175:web:2e0bdfa77eb19395c34f22',
    messagingSenderId: '532692727175',
    projectId: 'lab10-firebase-auth',
    authDomain: 'lab10-firebase-auth.firebaseapp.com',
    storageBucket: 'lab10-firebase-auth.firebasestorage.app',
  );
}
